#!/bin/sh
set -e

# try to insert the mapper entry to the "passwd" and "shadow" lines in
# /etc/nsswitch.conf to automatically enable libnss-mapper support; do not
# change the configuration if the lines already contain "mapper"
insert_nss_entry() {
    echo "Checking NSS setup..."
    # abort if /etc/nsswitch.conf does not exist
    if ! [ -e /etc/nsswitch.conf ]; then
        echo "Could not find /etc/nsswitch.conf."
        return
    fi
    perl -i -pe '
        sub insert {
            my $line = shift;
            # this also splits on tab
            my @bits=split(" ", $line);
            # do not break configuration if the line already references
            # mapper
            if (grep { $_ eq "mapper"} @bits) {
                return $line;
            }
            # add mapper at the end
            return $line . " mapper";
        }
        s/^(passwd:\s+)(.*)/$1.insert($2)/e;
        s/^(shadow:\s+)(.*)/$1.insert($2)/e;
    ' /etc/nsswitch.conf
}

if [ "$1" = configure ]; then
    if [ -z "$2" ]; then
        echo "First installation detected..."
        # first install: setup the recommended configuration
        insert_nss_entry
    else
        # upgrade:
        version="$2"

        if dpkg --compare-versions "$version" lt "0.0.8-2~"; then
            echo "Inserting NSS entry if necessary (#919459)."
            insert_nss_entry
        fi
    fi
    ldconfig
fi
