[alias]
build_slim = "build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --release"

[build]
target = ["x86_64-unknown-linux-gnu"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
